INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   1e-05
        Training size:   1530
        Validation size: 170
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
        Mixed Precision: False
Epoch 1/5:   0%|          | 0/1530 [00:29<?, ?img/s]
Traceback (most recent call last):
  File "E:/Pytorch-UNet/train.py", line 191, in <module>
    amp=args.amp)
  File "E:/Pytorch-UNet/train.py", line 95, in train_net
    multiclass=True)
  File "E:\Pytorch-UNet\utils\dice_score.py", line 40, in dice_loss
    return 1 - fn(input, target, reduce_batch_first=True)
  File "E:\Pytorch-UNet\utils\dice_score.py", line 31, in multiclass_dice_coeff
    dice += dice_coeff(input[:, channel, ...], target[:, channel, ...], reduce_batch_first, epsilon)
  File "E:\Pytorch-UNet\utils\dice_score.py", line 12, in dice_coeff
    inter = torch.dot(input.reshape(-1), target.reshape(-1))
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
PyDev console: starting.
Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\213.6461.77\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 1, in Exec
    def Exec(exp, global_vars, local_vars=None):
  File "<input>", line 1, in <module>
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\torch\_tensor.py", line 245, in __repr__
    def __repr__(self):
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\torch\_tensor_str.py", line 413, in _str
    def _str(self):
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\torch\_tensor_str.py", line 287, in _str_intern
    def _str_intern(inp):
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\torch\_tensor_str.py", line 223, in _tensor_str
    def _tensor_str(self, indent):
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\torch\_tensor_str.py", line 270, in get_summarized_data
    def get_summarized_data(self):
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\torch\_tensor_str.py", line 285, in <listcomp>
    return torch.stack([get_summarized_data(x) for x in self])
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\torch\_tensor_str.py", line 270, in get_summarized_data
    def get_summarized_data(self):
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\torch\_tensor_str.py", line 283, in <listcomp>
    return torch.stack([get_summarized_data(x) for x in (start + end)])
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\torch\_tensor_str.py", line 270, in get_summarized_data
    def get_summarized_data(self):
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\213.6461.77\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 1, in Exec
    def Exec(exp, global_vars, local_vars=None):
  File "<input>", line 1, in <module>
NameError: name 'inter' is not defined