2022-01-11 09:55:00,328 INFO    MainThread:11960 [wandb_setup.py:_flush():71] setting env: {}
2022-01-11 09:55:00,328 INFO    MainThread:11960 [wandb_setup.py:_flush():71] setting login settings: {'anonymous': 'must'}
2022-01-11 09:55:00,328 INFO    MainThread:11960 [wandb_init.py:_log_setup():371] Logging user logs to E:\Pytorch-UNet\wandb\run-20220111_095500-1kpubdr8\logs\debug.log
2022-01-11 09:55:00,328 INFO    MainThread:11960 [wandb_init.py:_log_setup():372] Logging internal logs to E:\Pytorch-UNet\wandb\run-20220111_095500-1kpubdr8\logs\debug-internal.log
2022-01-11 09:55:00,329 INFO    MainThread:11960 [wandb_init.py:init():404] calling init triggers
2022-01-11 09:55:00,329 INFO    MainThread:11960 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-01-11 09:55:00,330 INFO    MainThread:11960 [wandb_init.py:init():449] starting backend
2022-01-11 09:55:00,330 INFO    MainThread:11960 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2022-01-11 09:55:00,336 INFO    MainThread:11960 [backend.py:ensure_launched():199] starting backend process...
2022-01-11 09:55:00,775 INFO    MainThread:11960 [backend.py:ensure_launched():205] started backend process with pid: 64760
2022-01-11 09:55:00,775 INFO    MainThread:11960 [wandb_init.py:init():458] backend started and connected
2022-01-11 09:55:00,777 INFO    MainThread:11960 [wandb_init.py:init():519] updated telemetry
2022-01-11 09:55:00,831 INFO    MainThread:11960 [wandb_init.py:init():549] communicating current version
2022-01-11 09:55:01,757 INFO    MainThread:11960 [wandb_init.py:init():554] got version response 
2022-01-11 09:55:01,757 INFO    MainThread:11960 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-01-11 09:55:31,758 INFO    MainThread:11960 [interface_queue.py:_communicate_run():336] couldn't get run from backend
2022-01-11 09:55:31,758 ERROR   MainThread:11960 [wandb_init.py:init():569] backend process timed out
2022-01-11 09:55:31,758 ERROR   MainThread:11960 [wandb_init.py:init():578] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-01-11 09:57:33,643 WARNING MainThread:11960 [wandb_init.py:init():938] interrupted
Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\wandb_init.py", line 917, in init
    run = wi.init()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\wandb_init.py", line 582, in init
    backend.cleanup()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\backend\backend.py", line 230, in cleanup
    self.wandb_process.join()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\multiprocessing\process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\multiprocessing\popen_spawn_win32.py", line 80, in wait
    res = _winapi.WaitForSingleObject(int(self._handle), msecs)
KeyboardInterrupt
