2022-01-14 17:18:25,641 INFO    MainThread:15764 [wandb_setup.py:_flush():71] setting env: {}
2022-01-14 17:18:25,641 INFO    MainThread:15764 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-14 17:18:25,641 INFO    MainThread:15764 [wandb_init.py:_log_setup():371] Logging user logs to E:\Pytorch-UNet\wandb\run-20220114_171825-2nsgzlip\logs\debug.log
2022-01-14 17:18:25,642 INFO    MainThread:15764 [wandb_init.py:_log_setup():372] Logging internal logs to E:\Pytorch-UNet\wandb\run-20220114_171825-2nsgzlip\logs\debug-internal.log
2022-01-14 17:18:25,642 INFO    MainThread:15764 [wandb_init.py:init():404] calling init triggers
2022-01-14 17:18:25,642 INFO    MainThread:15764 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-01-14 17:18:25,643 INFO    MainThread:15764 [wandb_init.py:init():449] starting backend
2022-01-14 17:18:25,643 INFO    MainThread:15764 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2022-01-14 17:18:25,649 INFO    MainThread:15764 [backend.py:ensure_launched():199] starting backend process...
2022-01-14 17:18:26,034 INFO    MainThread:15764 [backend.py:ensure_launched():205] started backend process with pid: 23784
2022-01-14 17:18:26,035 INFO    MainThread:15764 [wandb_init.py:init():458] backend started and connected
2022-01-14 17:18:26,037 INFO    MainThread:15764 [wandb_init.py:init():519] updated telemetry
2022-01-14 17:18:26,081 INFO    MainThread:15764 [wandb_init.py:init():549] communicating current version
2022-01-14 17:18:27,654 INFO    MainThread:15764 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-01-14 17:18:27,654 INFO    MainThread:15764 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-01-14 17:18:57,656 INFO    MainThread:15764 [interface_queue.py:_communicate_run():336] couldn't get run from backend
2022-01-14 17:18:57,656 ERROR   MainThread:15764 [wandb_init.py:init():569] backend process timed out
2022-01-14 17:18:57,656 ERROR   MainThread:15764 [wandb_init.py:init():578] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-01-14 17:18:57,672 ERROR   MainThread:15764 [wandb_init.py:init():944] error
Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\wandb_init.py", line 917, in init
    run = wi.init()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\wandb_init.py", line 582, in init
    backend.cleanup()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\backend\backend.py", line 228, in cleanup
    self.interface.join()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 481, in join
    super(InterfaceQueue, self).join()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\interface\interface.py", line 591, in join
    self._communicate_shutdown()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 478, in _communicate_shutdown
    _ = self._communicate(record)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 237, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
