2022-01-11 11:23:17,937 INFO    MainThread:46084 [internal.py:wandb_internal():90] W&B internal server running at pid: 46084, started at: 2022-01-11 11:23:17.937226
2022-01-11 11:23:17,942 INFO    WriterThread:46084 [datastore.py:open_for_write():77] open: E:\Pytorch-UNet\wandb\run-20220111_112314-2ajxewi8\run-2ajxewi8.wandb
2022-01-11 11:23:17,944 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: check_version
2022-01-11 11:23:17,950 DEBUG   SenderThread:46084 [sender.py:send():238] send: header
2022-01-11 11:23:17,950 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: check_version
2022-01-11 11:23:19,053 DEBUG   SenderThread:46084 [sender.py:send():238] send: run
2022-01-11 11:23:19,061 INFO    SenderThread:46084 [sender.py:_maybe_setup_resume():506] checking resume status for None/U-Net/2ajxewi8
2022-01-11 11:23:19,868 INFO    SenderThread:46084 [dir_watcher.py:__init__():169] watching files in: E:\Pytorch-UNet\wandb\run-20220111_112314-2ajxewi8\files
2022-01-11 11:23:19,869 INFO    SenderThread:46084 [sender.py:_start_run_threads():828] run started: 2ajxewi8 with start time 1641871396
2022-01-11 11:23:19,869 DEBUG   SenderThread:46084 [sender.py:send():238] send: summary
2022-01-11 11:23:19,871 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: run_start
2022-01-11 11:23:19,875 INFO    SenderThread:46084 [sender.py:_save_file():960] saving file wandb-summary.json with policy end
2022-01-11 11:23:19,900 DEBUG   HandlerThread:46084 [meta.py:__init__():40] meta init
2022-01-11 11:23:19,900 DEBUG   HandlerThread:46084 [meta.py:__init__():54] meta init done
2022-01-11 11:23:19,900 DEBUG   HandlerThread:46084 [meta.py:probe():214] probe
2022-01-11 11:23:20,039 DEBUG   HandlerThread:46084 [meta.py:_setup_git():204] setup git
2022-01-11 11:23:20,209 DEBUG   HandlerThread:46084 [meta.py:_setup_git():211] setup git done
2022-01-11 11:23:20,210 DEBUG   HandlerThread:46084 [meta.py:_save_pip():58] save pip
2022-01-11 11:23:20,211 DEBUG   HandlerThread:46084 [meta.py:_save_pip():72] save pip done
2022-01-11 11:23:20,211 DEBUG   HandlerThread:46084 [meta.py:_save_conda():79] save conda
2022-01-11 11:23:20,877 INFO    Thread-17 :46084 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_112314-2ajxewi8\files\wandb-summary.json
2022-01-11 11:23:20,878 INFO    Thread-17 :46084 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_112314-2ajxewi8\files\requirements.txt
2022-01-11 11:23:20,879 INFO    Thread-17 :46084 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_112314-2ajxewi8\files\conda-environment.yaml
2022-01-11 11:23:25,885 INFO    Thread-17 :46084 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_112314-2ajxewi8\files\output.log
2022-01-11 11:23:26,886 INFO    Thread-17 :46084 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_112314-2ajxewi8\files\conda-environment.yaml
2022-01-11 11:23:27,888 INFO    Thread-17 :46084 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_112314-2ajxewi8\files\output.log
2022-01-11 11:23:28,101 DEBUG   HandlerThread:46084 [meta.py:_save_conda():89] save conda done
2022-01-11 11:23:28,101 DEBUG   HandlerThread:46084 [meta.py:probe():252] probe done
2022-01-11 11:23:28,115 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:23:28,116 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:23:28,505 DEBUG   SenderThread:46084 [sender.py:send():238] send: config
2022-01-11 11:23:28,506 DEBUG   SenderThread:46084 [sender.py:send():238] send: files
2022-01-11 11:23:28,508 INFO    SenderThread:46084 [sender.py:_save_file():960] saving file wandb-metadata.json with policy now
2022-01-11 11:23:28,891 INFO    Thread-17 :46084 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_112314-2ajxewi8\files\conda-environment.yaml
2022-01-11 11:23:28,891 INFO    Thread-17 :46084 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_112314-2ajxewi8\files\wandb-metadata.json
2022-01-11 11:23:29,485 INFO    Thread-22 :46084 [upload_job.py:push():137] Uploaded file C:\Users\211001~1.WXC\AppData\Local\Temp\tmp8o7wjh1lwandb\2hdm1xpk-wandb-metadata.json
2022-01-11 11:23:43,507 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:23:43,508 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:23:49,700 DEBUG   SenderThread:46084 [sender.py:send():238] send: stats
2022-01-11 11:23:49,921 INFO    Thread-17 :46084 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_112314-2ajxewi8\files\config.yaml
2022-01-11 11:23:58,874 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:23:58,875 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:24:14,247 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:24:14,248 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:24:21,761 DEBUG   SenderThread:46084 [sender.py:send():238] send: stats
2022-01-11 11:24:29,776 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:24:29,776 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:24:45,136 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:24:45,137 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:24:53,582 DEBUG   SenderThread:46084 [sender.py:send():238] send: stats
2022-01-11 11:25:00,506 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:25:00,506 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:25:15,896 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:25:15,897 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:25:25,536 DEBUG   SenderThread:46084 [sender.py:send():238] send: stats
2022-01-11 11:25:31,266 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:25:31,266 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:25:46,633 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:25:46,633 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:25:57,581 DEBUG   SenderThread:46084 [sender.py:send():238] send: stats
2022-01-11 11:26:02,035 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:26:02,036 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:26:17,415 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:26:17,415 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:26:29,487 DEBUG   SenderThread:46084 [sender.py:send():238] send: stats
2022-01-11 11:26:32,792 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:26:32,793 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:26:48,174 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:26:48,175 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:27:01,348 DEBUG   SenderThread:46084 [sender.py:send():238] send: stats
2022-01-11 11:27:03,558 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:27:03,559 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:27:18,932 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:27:18,932 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:27:33,158 DEBUG   SenderThread:46084 [sender.py:send():238] send: stats
2022-01-11 11:27:34,309 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:27:34,309 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:27:49,675 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:27:49,675 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:28:04,991 DEBUG   SenderThread:46084 [sender.py:send():238] send: stats
2022-01-11 11:28:05,042 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:28:05,043 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:28:20,424 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:28:20,424 DEBUG   SenderThread:46084 [sender.py:send_request():252] send_request: stop_status
2022-01-11 11:28:23,955 ERROR   SenderThread:46084 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connection.py", line 507, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\ssl.py", line 817, in __init__
    self.do_handshake()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\internal\internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))
2022-01-11 11:28:40,426 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:28:55,274 WARNING FileStreamThread:46084 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2ajxewi8/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000025359CBE198>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2ajxewi8/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 11:28:57,596 WARNING FileStreamThread:46084 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2ajxewi8/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000025359CBE198>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2ajxewi8/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 11:29:00,427 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:29:02,551 WARNING FileStreamThread:46084 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2ajxewi8/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000025359CBE198>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2ajxewi8/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 11:29:12,020 WARNING FileStreamThread:46084 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2ajxewi8/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000025359CBE198>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2ajxewi8/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 11:29:20,429 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:29:31,751 WARNING FileStreamThread:46084 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2ajxewi8/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000025359CBE198>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2ajxewi8/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 11:29:40,430 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:30:00,432 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:30:07,331 WARNING FileStreamThread:46084 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2ajxewi8/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000025359CBE198>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2ajxewi8/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 11:30:20,434 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:30:40,449 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:31:00,441 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:31:14,112 WARNING FileStreamThread:46084 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2ajxewi8/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000025359CBE198>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2ajxewi8/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 11:31:20,443 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 11:31:29,589 WARNING MainThread:46084 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-01-11 11:31:31,027 DEBUG   HandlerThread:46084 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 11:31:31,741 INFO    Thread-17 :46084 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_112314-2ajxewi8\files\output.log
